       SUBROUTINE I_LEE_DCD (F_DCD, NATOMS, NFRAMES)
       IMPLICIT NONE

       INTEGER NTOT
       COMMON /INDICES/ NTOT
       SAVE /INDICES/

       INTEGER F_DCD, NATOMS, NFRAMES

       INTEGER I

       CHARACTER*4 DUMMYC
       INTEGER DUMMYI
       REAL DUMMYR

       OPEN(F_DCD, file='trajectory.dcd', FORM='UNFORMATTED',
     &      status='OLD')
       READ(F_DCD) DUMMYC, NFRAMES, (DUMMYI, I=1, 8), DUMMYR,
     &          (DUMMYI, I=1, 9)
       READ(F_DCD) DUMMYI, DUMMYR
       READ(F_DCD) NATOMS

       NTOT = NATOMS

       RETURN
       END

CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

       SUBROUTINE LEE_DCD (F_DCD, X)
       IMPLICIT NONE

       INTEGER N1, N2, NTOT
       COMMON /INDICES/ NTOT
       SAVE /INDICES/

       INTEGER F_DCD
       REAL X(3, NTOT)

       REAL DUMMYR
       INTEGER I

       READ(F_DCD)  DUMMYR
       READ(F_DCD) (X(1, I), I=1, NTOT)
       READ(F_DCD) (X(2, I), I=1, NTOT)
       READ(F_DCD) (X(3, I), I=1, NTOT)

       RETURN
       END

CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      SUBROUTINE C_LEE_DCD (F_DCD)
      INTEGER F_DCD

      CLOSE(F_DCD)

      RETURN
      END
