CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C lector_dcd.f
C
C Pertenece al programa C-FORTRAN.
C
C Autor: DHR
C
C Creado: lun dic 14 00:46:27 ART 2009
C Editado: lun dic 14 00:46:27 ART 2009
C
C Rutinas de lectura de trayectoria dcd.
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC


       SUBROUTINE I_LEE_DCD (F_DCD, NATOMS, NFRAMES)
       IMPLICIT NONE

       INTEGER F_DCD, NATOMS, NFRAMES

       INTEGER I

       CHARACTER*4 DUMMYC
       INTEGER DUMMYI
       REAL DUMMYR

       OPEN(F_DCD, file='trajectory.dcd', FORM='UNFORMATTED',
     &      status='OLD')
       READ(F_DCD) DUMMYC, NFRAMES, (DUMMYI, I=1, 8), DUMMYR,
     &          (DUMMYI, I=1, 9)
       READ(F_DCD) DUMMYI, DUMMYR
       READ(F_DCD) NATOMS

       RETURN
       END

CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

       SUBROUTINE LEE_DCD (F_DCD, NATOMS, X)
       IMPLICIT NONE

       INTEGER NATOMS

       INTEGER F_DCD
       REAL X(3, NATOMS)

       REAL DUMMYR
       INTEGER I

       READ(F_DCD)  DUMMYR
       READ(F_DCD) (X(1, I), I=1, NATOMS)
       READ(F_DCD) (X(2, I), I=1, NATOMS)
       READ(F_DCD) (X(3, I), I=1, NATOMS)

       RETURN
       END

CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      SUBROUTINE C_LEE_DCD (F_DCD)
      INTEGER F_DCD

      CLOSE(F_DCD)

      RETURN
      END
